default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: admin
  host: localhost

development:
  <<: *default
  database: ajuda4_development

test:
  <<: *default
  database: ajuda4_test

production:
  <<: *default
  database: ajuda4_production
  username: ajuda4
  password: <%= ENV['AJUDA4_DATABASE_PASSWORD'] %>