# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Lawyer.create(email: 'advogado1@gmail.com', password: '123456', state:'AC', name: 'Advogado1')
Lawyer.create(email: 'advogado2@gmail.com', password: '123456', state:'AL', name: 'Advogado2')
Lawyer.create(email: 'advogado3@gmail.com', password: '123456', state:'AP', name: 'Advogado3')
Lawyer.create(email: 'advogado4@gmail.com', password: '123456', state:'AM', name: 'Advogado4')
Lawyer.create(email: 'advogado5@gmail.com', password: '123456', state:'BA', name: 'Advogado5')
Lawyer.create(email: 'advogado6@gmail.com', password: '123456', state:'CE', name: 'Advogado6')
Lawyer.create(email: 'advogado7@gmail.com', password: '123456', state:'DF', name: 'Advogado7')
Lawyer.create(email: 'advogado8@gmail.com', password: '123456', state:'ES', name: 'Advogado8')
Lawyer.create(email: 'advogado9@gmail.com', password: '123456', state:'GO', name: 'Advogado9')
Lawyer.create(email: 'advogado10@gmail.com', password: '123456', state:'MA', name: 'Advogado10')
Lawyer.create(email: 'advogado11@gmail.com', password: '123456', state:'MT', name: 'Advogado11')
Lawyer.create(email: 'advogado12@gmail.com', password: '123456', state:'MS', name: 'Advogado12')
Lawyer.create(email: 'advogado13@gmail.com', password: '123456', state:'MG', name: 'Advogado13')
Lawyer.create(email: 'advogado14@gmail.com', password: '123456', state:'PA', name: 'Advogado14')
Lawyer.create(email: 'advogado15@gmail.com', password: '123456', state:'PB', name: 'Advogado15')
Lawyer.create(email: 'advogado16@gmail.com', password: '123456', state:'PR', name: 'Advogado16')
Lawyer.create(email: 'advogado17@gmail.com', password: '123456', state:'PE', name: 'Advogado17')
Lawyer.create(email: 'advogado18@gmail.com', password: '123456', state:'PI', name: 'Advogado18')
Lawyer.create(email: 'advogado19@gmail.com', password: '123456', state:'RJ', name: 'Advogado19')
Lawyer.create(email: 'advogado20@gmail.com', password: '123456', state:'RN', name: 'Advogado20')
Lawyer.create(email: 'advogado21@gmail.com', password: '123456', state:'RS', name: 'Advogado21')
Lawyer.create(email: 'advogado22@gmail.com', password: '123456', state:'RO', name: 'Advogado22')
Lawyer.create(email: 'advogado23@gmail.com', password: '123456', state:'RR', name: 'Advogado23')
Lawyer.create(email: 'advogado24@gmail.com', password: '123456', state:'SC', name: 'Advogado24')
Lawyer.create(email: 'advogado25@gmail.com', password: '123456', state:'SP', name: 'Advogado25')
Lawyer.create(email: 'advogado26@gmail.com', password: '123456', state:'SE', name: 'Advogado26')
Lawyer.create(email: 'advogado27@gmail.com', password: '123456', state:'TO', name: 'Advogado27')
